version: "3.8"

# NginX container with reversed proxy and SSL certificates
services:
  nginx-server:
    build: ./requirements/nginx
    image: nginx-server
    container_name: nginx-server
    volumes:
      - wordpress_vol:/var/www/html
    ports:
      - "443:443"
    restart: on-failure

volumes:
  wordpress_vol:
    name: wordpress_vol
    driver_opts:
      type: none
      device: /home/mtavares/data
      o: bind

  networks:
  inception_network:
    name: inception
