version: "3.8"

# NginX container with reversed proxy and SSL certificates
services:
  nginx_server:
    build: ./requirements/nginx
    image: nginx_server
    container_name: nginx_server
    volumes:
      - wordpress_vol:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress_site
    networks:
      - inception
    restart: on-failure

  mariadb_db:
    build: ./requirements/mariadb
    image: mariadb_db
    container_name: mariadb_db
    env_file:
        - .env
    volumes:
      - database:/var/lib/mysql
    networks:
        - inception
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent"]
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 5s
    restart: on-failure

  wordpress_site:
    build: ./requirements/wordpress
    image: wordpress_site
    container_name: wordpress_site
    env_file:
      - .env
    volumes:
      - wordpress_vol:/var/www/html
    depends_on:
      mariadb_db:
        condition: service_healthy
    networks:
      - inception
    restart: on-failure


volumes:
  wordpress_vol:
    name: wordpress_vol
    driver_opts:
      type: none
      device: /home/mtavares/data/wordpress/
      o: bind
  database:
    name: database
    driver_opts:
      type: none
      device: /home/mtavares/data/mysql/
      o: bind

networks:
  inception:
    name: inception
