version: '3.8'

services:
  web_server:
    build: ./requirements/nginx
    image: nginx:1.0
    container_name: web_Server
    ports:
      - 443:443
    depends_on:
      - site
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    restart: on-failure

  database:
    build: ./requirements/mariadb
    image: mariadb:1.0
    container_name: database
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    restart: on-failure
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent"]
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 5s
  
  site:
    build: ./requirements/wordpress
    image: wordpress:1.0
    container_name: site
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    restart: on-failure


volumes:
  db:
    name: db
    driver_opts:
      type: none
      device: /home/mtavares/data/mysql
      o: bind
  wp:
    name: wp
    driver_opts:
      type: none
      device: /home/mtavares/data/wordpress
      o: bind

networks:
  inception:
    name: inception
