version: "3"

# NginX container with reversed proxy and SSL certificates
services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    image: nginx
    volumes:
      - wordpress_vol:/var/www/html/wordpress
    ports:
      - "443:443"
    restart: on-failure

volumes:
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/mtavares/data
      o: bind
    name: wordpress_vol

  networks:
  inception_network:
    name: inception
